name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # La rama que contiene tu código fuente

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Construir proyecto
        run: npm run build  # Asegúrate de que este es el comando correcto

      - name: 🚀 Desplegar en GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: despliegue  # La rama donde se subirá el contenido de `dist`
          folder: dist       # Carpeta que se va a subir (ajustar según tu caso)

